import { chromium } from 'playwright';
const EXE='/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
let fail=0; const ck=(n,ok,x='')=>{console.log(`  ${ok?'✓':'✗'} ${n}${x?'  '+x:''}`); if(!ok)fail++;};
const b=await chromium.launch({executablePath:EXE});
const p=await b.newPage({viewport:{width:1000,height:1000}});
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
const F='file:///home/user/spanish_learning_website/dist-single/index.html';
await p.goto(F,{waitUntil:'load'}); await p.waitForTimeout(1500);
let t=await p.locator('main').innerText();
ck('單檔版首頁載入', /Bienvenido|旅程地圖/.test(t));
ck('連續天數卡在單檔版也在', /還沒開始連續紀錄|連續/.test(t));
ck('旅程地圖節點', (await p.locator('div[role="img"] > div').count())===5);
await p.goto(F+'#/achievements',{waitUntil:'load'}); await p.waitForTimeout(900);
t=await p.locator('main').innerText();
ck('hash 路由在 file:// 下可用', /已解鎖 \d+ \/ 26/.test(t), t.match(/已解鎖 \d+ \/ 26/)?.[0]??'');
ck('沒有 JS 例外', errs.length===0, errs.slice(0,2).join(' | '));
const tier = await p.evaluate(()=>localStorage.length>=0);
ck('儲存層可用', tier);
await p.screenshot({path:process.argv[2]+'/p4-single-file.png',fullPage:false});
console.log(fail?`${fail} 項失敗`:'單檔版全部通過');
await b.close(); process.exit(fail?1:0);
